In [3]:
import torch


a = torch.tensor([[1, 2], [1, 2], [3, 4], [5,0]])
a

tensor([[1, 2],
        [1, 2],
        [3, 4],
        [5, 0]])

In [9]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [10]:
b = a.to(device)

In [14]:
c = torch.ones(4,2).to(device)
c = c + b

In [16]:
j = 1
d = c[:, j]

In [32]:
f = torch.rand(4, 5, 8)
f = f.to(device)
f

tensor([[[0.7425, 0.3114, 0.5270, 0.3715, 0.9255, 0.7768, 0.0971, 0.0742],
         [0.5931, 0.0783, 0.8075, 0.5737, 0.8434, 0.8904, 0.7630, 0.5948],
         [0.4378, 0.0014, 0.5206, 0.8543, 0.4535, 0.4588, 0.1751, 0.2319],
         [0.4467, 0.4861, 0.7285, 0.7734, 0.1909, 0.3943, 0.1557, 0.8911],
         [0.5261, 0.6828, 0.4165, 0.0215, 0.8193, 0.9751, 0.4243, 0.2545]],

        [[0.1374, 0.4601, 0.3252, 0.4601, 0.7518, 0.9881, 0.0774, 0.7562],
         [0.2480, 0.3729, 0.0892, 0.9732, 0.1382, 0.5078, 0.6667, 0.7184],
         [0.2675, 0.1123, 0.9766, 0.1234, 0.8403, 0.4354, 0.7516, 0.3171],
         [0.8201, 0.6817, 0.6952, 0.4827, 0.0268, 0.9831, 0.1751, 0.9377],
         [0.4907, 0.1475, 0.9931, 0.3411, 0.9961, 0.9412, 0.7681, 0.1891]],

        [[0.5361, 0.1879, 0.7886, 0.6042, 0.4452, 0.1701, 0.5012, 0.8742],
         [0.5133, 0.3813, 0.8832, 0.4878, 0.9000, 0.5358, 0.4551, 0.3931],
         [0.9160, 0.4925, 0.3013, 0.4452, 0.7619, 0.8195, 0.7886, 0.8668],
         [0.3407, 0.3

In [35]:
f[:, 3, :]

tensor([[0.4467, 0.4861, 0.7285, 0.7734, 0.1909, 0.3943, 0.1557, 0.8911],
        [0.8201, 0.6817, 0.6952, 0.4827, 0.0268, 0.9831, 0.1751, 0.9377],
        [0.3407, 0.3514, 0.4817, 0.6389, 0.1275, 0.8100, 0.3017, 0.7511],
        [0.1472, 0.9963, 0.6415, 0.8347, 0.5710, 0.7191, 0.1607, 0.8953]],
       device='cuda:0')

In [44]:
mask = torch.zeros(4, 5, 8)
mask[0, 4, :] = torch.ones(1)
mask[1, 4, :] = torch.ones(1)
mask[2, 2, :] = torch.ones(1)
mask[3, 3, :] = torch.ones(1)
mask = mask.to(device)
mask

tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]], device='cuda:0')

In [46]:
f_masked = f * mask
f_masked

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5261, 0.6828, 0.4165, 0.0215, 0.8193, 0.9751, 0.4243, 0.2545]],

        [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.4907, 0.1475, 0.9931, 0.3411, 0.9961, 0.9412, 0.7681, 0.1891]],

        [[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.9160, 0.4925, 0.3013, 0.4452, 0.7619, 0.8195, 0.7886, 0.8668],
         [0.0000, 0.0

In [48]:
output = torch.sum(f_masked, dim=1)
output

tensor([[0.5261, 0.6828, 0.4165, 0.0215, 0.8193, 0.9751, 0.4243, 0.2545],
        [0.4907, 0.1475, 0.9931, 0.3411, 0.9961, 0.9412, 0.7681, 0.1891],
        [0.9160, 0.4925, 0.3013, 0.4452, 0.7619, 0.8195, 0.7886, 0.8668],
        [0.1472, 0.9963, 0.6415, 0.8347, 0.5710, 0.7191, 0.1607, 0.8953]],
       device='cuda:0')

In [49]:
output.size()

torch.Size([4, 8])

In [51]:
outs = torch.tensor([[0.2, 0.8],[0.4,0.6],[0.15,0.85],[0.5,0.5]])
outs

tensor([[0.2000, 0.8000],
        [0.4000, 0.6000],
        [0.1500, 0.8500],
        [0.5000, 0.5000]])

In [65]:
accum = torch.sum(outs, dim=0)
accum = accum.view(1, 2)
v, idx = torch.max(accum, dim=1)
v.item()

2.75